spring:
  application:
    name: spring-ai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-5.2
    retry:
      max-attempts: 3 #최대 재시도 횟수
      backoff:
        initial-interval: 1000 #ms 대기시간
        max-interval: 10000 #ms 최대 대기시간
        multiplier: 2 # 대기시간 증가 배수

# --------------------------------------------------
# Application-specific AI prompt configuration
# --------------------------------------------------
app:
  ai:
    openai:
      prompt:
        system-default:
          dir: "classpath:/prompt/system/"
          default:
            file-name: "system.ko.v1.md"
        style:
          dir: "classpath:/prompt/style/"
          templates:
            default:
              file-name: "default.ko.v1.md"
            conversation:
              file-name: "conversation.ko.v1.md"


  configure:
    conversation:
      max-history: 20